# Generated by Django 5.0.6 on 2025-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofiles_order_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='optional_address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='order_notes',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='street_address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
