# Generated by Django 5.0.6 on 2025-02-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0010_alter_category_cat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_type', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('Color', models.CharField(max_length=10)),
                ('Feature', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('Image', models.ImageField(upload_to='Categories')),
                ('product_image_1', models.ImageField(upload_to='Categories')),
                ('product_image_2', models.ImageField(upload_to='Categories')),
                ('product_image_3', models.ImageField(upload_to='Categories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
