# Generated by Django 5.0.6 on 2025-02-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '', 'verbose_name_plural': 'Store'},
        ),
    ]
