# Generated by Django 5.0.6 on 2025-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_store_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
