# Generated by Django 5.0.6 on 2025-02-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_store_image_alter_store_product_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Image',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_1',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_2',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_3',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
