# Generated by Django 5.0.6 on 2025-02-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_store_image_alter_store_product_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Feature',
            new_name='Feature_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Size',
        ),
        migrations.AddField(
            model_name='store',
            name='Color_1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Color_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Color_3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Feature_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Feature_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Materials_Care_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Materials_Care_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Materials_Care_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Size_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Size_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Size_3',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
