# Generated by Django 5.0.6 on 2025-02-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_store_color_2_alter_store_color_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
