# Generated by Django 5.0.6 on 2025-02-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_store_price_alter_store_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
