# Generated by Django 5.0.6 on 2025-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_alter_store_price_alter_store_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_type',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
