# Generated by Django 5.0.6 on 2025-02-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('luxury', 'Luxury')], max_length=50, null=True),
        ),
    ]
