# Generated by Django 5.0.6 on 2025-02-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='type',
        ),
    ]
