# Generated by Django 5.0.6 on 2025-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_remove_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Color_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='Color_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='Color_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
