# Generated by Django 5.0.6 on 2025-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_store_color_1_alter_store_color_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Color_1',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Feature_2',
            new_name='Materials_Care',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Color_2',
            new_name='Size',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Color_3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Feature_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Feature_3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Materials_Care_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Materials_Care_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Materials_Care_3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Size_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Size_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Size_3',
        ),
        migrations.AddField(
            model_name='store',
            name='Feature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_1',
            field=models.ImageField(blank=True, upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_2',
            field=models.ImageField(blank=True, upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_3',
            field=models.ImageField(blank=True, upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
