# Generated by Django 5.0.6 on 2025-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_rename_color_1_store_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Color',
            new_name='Color_1',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Size',
            new_name='Color_2',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Materials_Care',
            new_name='Feature_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Feature',
        ),
        migrations.AddField(
            model_name='store',
            name='Color_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Feature_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Feature_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Materials_Care_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Materials_Care_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Materials_Care_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Size_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Size_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Size_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='Image',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_1',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_2',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_image_3',
            field=models.ImageField(upload_to='Products'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
