# Generated by Django 5.0.6 on 2025-03-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_rename_color_store_color_1_rename_size_store_color_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Color_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Color_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Color_3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Feature_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Feature_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Feature_3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Materials_Care_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Materials_Care_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Materials_Care_3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Size_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Size_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Size_3',
        ),
    ]
