# Generated by Django 5.0.6 on 2025-03-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_remove_store_color_1_remove_store_color_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='product_name',
            new_name='name',
        ),
    ]
