# Generated by Django 5.0.6 on 2025-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_rename_image_store_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='sale',
            field=models.IntegerField(null=True),
        ),
    ]
