# Generated by Django 5.0.6 on 2025-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(max_length=10)),
                ('location_map_image', models.ImageField(upload_to='Locatoins-map')),
                ('location_svg_code', models.TextField(max_length=1000)),
                ('location_store_image', models.ImageField(upload_to='Locatoins-map')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Locations Map',
            },
        ),
    ]
