# Generated by Django 5.0.6 on 2025-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations_map',
            name='location_store_image',
            field=models.ImageField(blank=True, null=True, upload_to='Locatoins-map'),
        ),
    ]
