# Generated by Django 5.0.6 on 2025-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations_map', '0002_alter_locations_map_location_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations_map',
            name='location_svg_code',
            field=models.TextField(max_length=2000),
        ),
    ]
