# Generated by Django 5.0.6 on 2025-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations_map', '0005_remove_locations_map_location_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations_map',
            name='location_store_img',
            field=models.ImageField(null=True, upload_to='Locations-map'),
        ),
        migrations.AlterField(
            model_name='locations_map',
            name='location_map_image',
            field=models.ImageField(upload_to='Locations-map'),
        ),
    ]
