# Generated by Django 5.0.6 on 2025-02-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations_map', '0006_locations_map_location_store_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations_map',
            name='location_store_img',
            field=models.FileField(null=True, upload_to='Locations-map'),
        ),
    ]
