# Generated by Django 5.0.6 on 2025-02-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations_map', '0007_alter_locations_map_location_store_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations_map',
            name='location_store_img',
        ),
    ]
