# Generated by Django 5.0.6 on 2025-02-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations_map', '0009_locations_map_store_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations_map',
            old_name='store_img',
            new_name='img',
        ),
    ]
