# Generated by Django 5.0.6 on 2025-02-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '', 'verbose_name_plural': 'Categories'},
        ),
    ]
