# Generated by Django 5.0.6 on 2025-02-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_column_height',
            field=models.IntegerField(max_length=3),
        ),
    ]
