# Generated by Django 5.0.6 on 2025-02-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_alter_category_category_column_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_column_height',
        ),
    ]
