# Generated by Django 5.0.6 on 2025-02-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_remove_category_category_column_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_column_height',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
