# Generated by Django 5.0.6 on 2025-02-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_category_category_column_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_column_height',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_cat_1',
            field=models.ImageField(null=True, upload_to='Categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_cat_2',
            field=models.ImageField(null=True, upload_to='Categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_cat_3',
            field=models.ImageField(null=True, upload_to='Categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_cat_4',
            field=models.ImageField(null=True, upload_to='Categories'),
        ),
    ]
