# Generated by Django 5.0.6 on 2025-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0007_remove_category_category_column_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_cat_1',
            new_name='cat_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image_cat_2',
            new_name='cat_image_half_col',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_cat_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_cat_4',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_half_col_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_col_height',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
