# Generated by Django 5.0.6 on 2025-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_rename_image_cat_1_category_cat_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_half_col_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image_half_col',
            field=models.ImageField(blank=True, null=True, upload_to='Categories'),
        ),
    ]
