# Generated by Django 5.0.6 on 2025-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0009_alter_category_cat_half_col_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='Categories'),
        ),
    ]
