# Generated by Django 5.0.6 on 2025-02-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0010_alter_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_half_col_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_image_half_col',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_col_height',
        ),
    ]
