# Generated by Django 5.0.6 on 2025-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0012_category_type_category_type_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('FORMAL', 'Formal'), ('LUXURY', 'Luxury')], max_length=20, null=True),
        ),
    ]
