# Generated by Django 5.0.6 on 2025-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slider')),
                ('title', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
                ('link_name', models.CharField(max_length=15)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Hero Slider',
            },
        ),
    ]
