# Generated by Django 5.0.6 on 2025-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_Slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_slider',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
