# Generated by Django 5.0.6 on 2025-03-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0017_rename_color_store_color_1_rename_size_store_color_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('feature', models.TextField(max_length=60)),
                ('material_care', models.TextField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.store')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Product Variations',
            },
        ),
    ]
