# Generated by Django 5.0.6 on 2025-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variations',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product_variations',
            name='feature',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='product_variations',
            name='material_care',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product_variations',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
