# Generated by Django 5.0.6 on 2025-02-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(upload_to='site_logo')),
                ('theme_hero_section', models.ImageField(upload_to='theme_hero_section')),
                ('tax_rate', models.IntegerField()),
                ('product_policies', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
