# Generated by Django 5.0.6 on 2025-02-19 03:15

import Site_Settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_settings',
            name='site_logo',
            field=models.FileField(upload_to='site_logo', validators=[Site_Settings.models.validate_logo]),
        ),
    ]
