# Generated by Django 5.0.6 on 2025-02-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Settings', '0003_site_settings_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_settings',
            name='estimated_delivery',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site_settings',
            name='return_time',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
