# Generated by Django 5.0.6 on 2025-02-23 15:08

import Site_Settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Settings', '0004_alter_site_settings_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_settings',
            name='fav_icon',
            field=models.FileField(null=True, upload_to='fav_icon', validators=[Site_Settings.models.validate_logo]),
        ),
    ]
