# Generated by Django 5.0.6 on 2025-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('link_button_name', models.CharField(max_length=15)),
                ('button_link', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='Sale Section')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Sale Section',
            },
        ),
    ]
