# Generated by Django 5.0.6 on 2025-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale_Section', '0002_alter_sale_section_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_section',
            name='image',
            field=models.ImageField(upload_to='Sale_Section'),
        ),
    ]
