# Generated by Django 5.0.6 on 2025-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('timings', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Our_Locations')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Our Locations',
            },
        ),
    ]
