# Generated by Django 5.0.6 on 2025-02-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_locations',
            name='close_detail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
